import { CoachModel, OwnerModel } from "./types";

export const coachesData: CoachModel[] = [
  {
    id: 1,
    lastName: "Быков",
    firstName: "Евгений",
    patronymicName: "Валерьевич",
    description: "Ведущий тренер. «Не могу и дня без волейбола». Ведёт детские и взрослые группы",
    city: "Минск",
    src: "/coaches/bykov.webp",
    alt: "Фото тренера Евгения Быкова",
  },
  {
    id: 2,
    lastName: "Рыбко",
    firstName: "Александр",
    patronymicName: "Александрович",
    description: "Тренер детских и взрослых групп",
    city: "Минск",
    src: "/coaches/rybko.webp",
    alt: "Фото тренера Александра Рыбко",
  },
  {
    id: 3,
    lastName: "Гурский",
    firstName: "Игорь",
    patronymicName: "Александрович",
    description: "Тренер детских и взрослых групп",
    city: "Минск",
    src: "/coaches/gursky.webp",
    alt: "Фото тренера Игоря Гурского",
  },
  {
    id: 4,
    lastName: "Горбачева",
    firstName: "Ангелина",
    patronymicName: "Александровна",
    description: "Тренер детских и взрослых групп",
    city: "Минск",
    src: "/coaches/gorbacheva.webp",
    alt: "Фото тренера Ангелины Горбачевой",
  },
  {
    id: 5,
    lastName: "Киселев",
    firstName: "Егор",
    patronymicName: "Игоревич",
    description: "Тренер детских и взрослых групп",
    city: "Минск",
    src: "/coaches/kiselyov.webp",
    alt: "Фото тренера Ангелины Горбачевой",
  },
  {
    id: 6,
    lastName: "Крупко",
    firstName: "Виктория",
    patronymicName: "Анатольевна",
    description: "Ведущий детский тренер.  Опыт работы с детьми - более 10 лет",
    city: "Брест",
    src: "/coaches/krupko.webp",
    alt: "Фото тренера Виктории Крупко",
  },
  {
    id: 7,
    lastName: "Андриевич",
    firstName: "Наталья",
    patronymicName: "Павловна",
    description: "Детский тренер",
    city: "Брест",
    src: "/coaches/andrievich.webp",
    alt: "Фото тренера Натальи Андриевич",
  },
  {
    id: 8,
    lastName: "Сабиров",
    firstName: "Владислав",
    patronymicName: "Денисович",
    description: "Детский тренер",
    city: "Брест",
    src: "/coaches/sabirov.webp",
    alt: "Фото тренера Владислава Сабирова",
  },
] as const;

export const ownerData: OwnerModel = {
  lastName: "Голодухин",
  firstName: "Владислав",
  description:
    "Мы смотрим на наших учеников не с позиции: “Каких высот он может или не может достичь в волейболе”, а с позиции: “Как мы можем помочь стать лучше через волейбол. ”Если вы разделяете наши ценности и ищете не просто занятие волейболом, а также поддержку ребенка в развитии, мы будем рады видеть вас в нашей дружной команде.",
  src: "/coaches/golodukhin.webp",
  alt: "Фото тренера Владислава Голодухина",
} as const;
