export { Banner } from "@/widgets/banner";
export { Advantages } from "@/widgets/advantages";
export { ContactForm } from "@/widgets/contact-form";
export { Faq } from "@/widgets/faq";
export { Hero } from "@/widgets/hero";
export { Footer } from "@/widgets/footer";
export { Header } from "@/widgets/header";
export { Coaches } from "@/widgets/coaches";
export { Gallery } from "@/widgets/gallery";
